name: dripolini
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21
  - pillow
  - scikit-learn
  - pip:
      - deepface==0.0.83
      - opencv-python==4.7.0.72
      - tensorflow==2.13.0
      - streamlit==1.45.1
      - ultralytics
      - google-generativeai
      - gradio_client