name: informatyka_afektywna
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21
  - pillow
  - pip:
      - deepface==0.0.83
      - opencv-python==4.7.0.72
      - tensorflow==2.13.0
      - streamlit==1.34.0
      - ultralytics
      - scikit-learn
      - google-generativeai

